### PR TITLE
Feature/drag and drop 45

### PR DESCRIPTION
**Pull request by nirlipo**
We are now trying to integrate the contributions through a
1- fork-> branch -> develop, instead of 
2- fork -> develop

 See PR https://github.com/planimation/frontend/pull/52 for information on the failed attend using method 2

### CODE REVIEW

**Comment by nirlipo** [comment]
@Ojeechan , we exchanged roles now. I created the PR, check that the commits are the correct one, and if travis passes all the tests, then we/you can click on merge

**Comment by nirlipo** [comment]
@YIDING-CODER your method got us passed the licence issue, thanks!

We created the branch, pushed the code there, and did a PR from that branch to develop. Now travis seems to get stuck while building. Have you seen this issue before?

https://travis-ci.org/github/planimation/frontend/builds/689126549

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by Ojeechan** [comment]
@nirlipo 
I previously changed Dockerfile(https://github.com/planimation/frontend/blob/develop/docker/release/Dockerfile) in order to get a log file,

originally from
`RUN ${UNITY_PATH} ${UNITY_ARGS} ${PROJECT_PATH} -executeMethod ${BUILD_SCRIPT} -logFile`

to
`RUN ${UNITY_PATH} ${UNITY_ARGS} -projectPath ${PROJECT_PATH} -executeMethod ${BUILD_SCRIPT} -logFile ${LOGFILE}`

Does it have some relationship to that error?

**Comment by YIDING-CODER** [comment]
> @nirlipo
> I previously changed Dockerfile(https://github.com/planimation/frontend/blob/develop/docker/release/Dockerfile) in order to get a log file,
> 
> originally from
> `RUN ${UNITY_PATH} ${UNITY_ARGS} ${PROJECT_PATH} -executeMethod ${BUILD_SCRIPT} -logFile`
> 
> to
> `RUN ${UNITY_PATH} ${UNITY_ARGS} -projectPath ${PROJECT_PATH} -executeMethod ${BUILD_SCRIPT} -logFile ${LOGFILE}`
> 
> Does it have some relationship to that error?

**Comment by YIDING-CODER** [comment]
Hi Nir,

emmm, I haven't seen this issue before. The CI/CD process for front-end is
very interesting, sometimes everything looks correct but it is not working.

Can they try the following steps?

0. Changed the Dockerfile back to the original one, and then try again.
1. Make a pull request without changing any code but add some comments, and
see whether the Pipe Line is working or not.
2. Try to manually build the Unity WebGL files in Unity.
3. If step1&2 Pass, I feel like it is caused by the auto-generated
files. *Delete
all the files in the library folder,* then open and load the project in
unity and all the meta files should be updated after that(I can see the
source file is updated, but the meta files is 9 months old). Finally, try
to commit and make a PR.

Good luck!

Thank you.
Regards,
Yi

**Pull request closed without merging**
